# Generated by Django 4.1.4 on 2022-12-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldal',
            name='hatter',
            field=models.ImageField(upload_to='images'),
        ),
    ]
