# Generated by Django 4.1.4 on 2022-12-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldal', '0004_cim_hatter_delete_oldal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oldal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatter', models.ImageField(upload_to='static/images')),
                ('cim', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Cim',
        ),
        migrations.DeleteModel(
            name='Hatter',
        ),
    ]
