# Generated by Django 4.1.4 on 2022-12-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldal', '0006_cimek_remove_oldal_cim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldal',
            name='hatter',
            field=models.ImageField(upload_to='staticfiles/images'),
        ),
    ]
