# Generated by Django 4.1.4 on 2022-12-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldal', '0007_alter_oldal_hatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldal',
            name='hatter',
            field=models.FileField(upload_to='staticfiles/images'),
        ),
    ]
