# Generated by Django 4.1.4 on 2022-12-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldal', '0013_alter_oldal_hatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldal',
            name='hatter',
            field=models.FileField(upload_to='media_root'),
        ),
    ]
